import { RISK_LEVEL } from './types';

export const mockData = [
  {
    id: 1,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: null,
    totalSpend: 450,
    confirmationRate: 87,
    performanceScore: 93,
    riskLevel: RISK_LEVEL.low,
  },
  {
    id: 2,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 1050,
    confirmationRate: 87,
    performanceScore: 75,
    riskLevel: RISK_LEVEL.low,
  },
  {
    id: 3,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 2500,
    confirmationRate: 87,
    performanceScore: 75,
    riskLevel: RISK_LEVEL.medium,
  },
  {
    id: 4,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 1000,
    confirmationRate: 70,
    performanceScore: 20,
    riskLevel: RISK_LEVEL.high,
  },
  {
    id: 5,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 1000,
    confirmationRate: 70,
    performanceScore: 20,
    riskLevel: RISK_LEVEL.high,
  },
  {
    id: 6,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: null,
    totalSpend: 450,
    confirmationRate: 87,
    performanceScore: 93,
    riskLevel: RISK_LEVEL.low,
  },
  {
    id: 7,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 2500,
    confirmationRate: 87,
    performanceScore: 75,
    riskLevel: RISK_LEVEL.medium,
  },
  {
    id: 8,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 2500,
    confirmationRate: 87,
    performanceScore: 75,
    riskLevel: RISK_LEVEL.medium,
  },
  {
    id: 9,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: 'vendor@example.com',
    totalSpend: 2500,
    confirmationRate: 87,
    performanceScore: 75,
    riskLevel: RISK_LEVEL.medium,
  },
  {
    id: 10,
    vendorName: 'Big Kahuna Burger Ltd.',
    email: null,
    totalSpend: 450,
    confirmationRate: 87,
    performanceScore: 93,
    riskLevel: RISK_LEVEL.low,
  },
];
